In [1]:
import sys
sys.path.append("..")

In [2]:
import numpy as np
import pandas as pd

from src.data import *
from src.utils import *
from src.model import *
from src.recourse import *

In [3]:
# from fairlearn.datasets import fetch_acs_income
# df = fetch_acs_income(cache=True, as_frame=True, return_X_y=False)
# df_full = df.frame
# df_full

In [4]:
def scale_num_features(df: pd.DataFrame, num_features: List[str]):
    scaler = StandardScaler()
    df[num_features] = scaler.fit_transform(df[num_features].values)
    return df

def getACSIncomeData():
    df = pd.read_pickle("../datasets/acs_income.pkl")
    cat_features = ['COW', 'SCHL', 'MAR', 'RELP', 'SEX', 'RAC1P']
    num_features = ['AGEP', 'WKHP']

    df = df.sample(frac=1, random_state=0)
    
    df.drop(columns=['OCCP', 'POBP'], inplace=True)

    df["SCHL_new"] = df["SCHL"].apply(lambda x: 1 if x <= 15 else (x - 14))
    df["SCHL"] = df["SCHL_new"]
    df.drop(columns=["SCHL_new"], inplace=True)

    df = pd.get_dummies(df, columns=cat_features, dtype=float)
    df = scale_num_features(df, num_features=num_features)
    df['PINCP'] = df['PINCP'].apply(lambda x: 1 if x >= 50000 else 0)

    y = df['PINCP']
    X = df.drop(columns=['PINCP'])

    return X, y

In [24]:
df_full = pd.read_pickle("../datasets/acs_income.pkl").sample(frac=1, random_state=0)
df_full

         AGEP  COW  SCHL  MAR    OCCP   POBP  RELP  WKHP  SEX  RAC1P     PINCP
1645316  40.0  1.0  21.0  3.0  5740.0   55.0   0.0  40.0  2.0    1.0   40700.0
924583   37.0  1.0  19.0  1.0  8740.0  128.0   0.0  40.0  2.0    1.0   38000.0
682734   59.0  4.0  24.0  3.0  2205.0   36.0   0.0  40.0  1.0    2.0  197000.0
790940   28.0  1.0  21.0  5.0  1460.0   26.0   0.0  40.0  1.0    1.0   90000.0
68445    44.0  2.0  21.0  1.0  3255.0    6.0   0.0  40.0  2.0    1.0   38000.0
...       ...  ...   ...  ...     ...    ...   ...   ...  ...    ...       ...
152315   17.0  1.0  16.0  5.0  4720.0    6.0   2.0  12.0  2.0    1.0     500.0
963395   55.0  4.0  16.0  1.0  5720.0    8.0   1.0  24.0  2.0    1.0   36000.0
117952   72.0  1.0  19.0  3.0  5400.0    6.0   0.0  40.0  2.0    1.0   48700.0
1484405  55.0  1.0  16.0  3.0  6200.0   35.0   2.0  50.0  1.0    1.0   80000.0
305711   75.0  1.0  23.0  1.0   860.0    9.0   1.0  50.0  1.0    1.0  147000.0

[1664500 rows x 11 columns]

In [17]:
df_full.describe()

,AGEP,COW,SCHL,MAR,OCCP,POBP,RELP,WKHP,SEX,RAC1P,PINCP
count,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06
mean,4.341127e+01,2.077500e+00,1.861814e+01,2.521997e+00,4.180517e+03,6.581708e+01,2.241254e+00,3.833390e+01,1.479282e+00,1.874745e+00,5.666386e+04
std,1.530203e+01,1.825338e+00,3.297826e+00,1.796720e+00,2.658717e+03,9.306245e+01,4.385288e+00,1.308073e+01,4.995707e-01,2.084384e+00,7.306745e+04
min,1.700000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+01,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.040000e+02
25%,3.000000e+01,1.000000e+00,1.600000e+01,1.000000e+00,2.205000e+03,1.800000e+01,0.000000e+00,3.500000e+01,1.000000e+00,1.000000e+00,2.000000e+04
50%,4.300000e+01,1.000000e+00,1.900000e+01,1.000000e+00,4.200000e+03,3.600000e+01,1.000000e+00,4.000000e+01,1.000000e+00,1.000000e+00,3.900000e+04
75%,5.600000e+01,3.000000e+00,2.100000e+01,5.000000e+00,5.740000e+03,4.800000e+01,2.000000e+00,4.400000e+01,2.000000e+00,1.000000e+00,6.800000e+04
max,9.600000e+01,8.000000e+00,2.400000e+01,5.000000e+00,9.830000e+03,5.540000e+02,1.700000e+01,9.900000e+01,2.000000e+00,9.000000e+00,1.423000e+06

In [46]:
df_full.drop(columns=['OCCP', 'POBP'], inplace=True)

In [47]:
df_full

         AGEP  COW  SCHL  MAR  RELP  WKHP  SEX  RAC1P    PINCP
0        18.0  1.0  18.0  5.0  17.0  21.0  2.0    2.0   1600.0
1        53.0  5.0  17.0  5.0  16.0  40.0  1.0    1.0  10000.0
2        41.0  1.0  16.0  5.0  17.0  40.0  1.0    1.0  24000.0
3        18.0  6.0  18.0  5.0  17.0   2.0  2.0    1.0    180.0
4        21.0  5.0  19.0  5.0  17.0  50.0  1.0    1.0  29000.0
...       ...  ...   ...  ...   ...   ...  ...    ...      ...
1664495  39.0  6.0  16.0  5.0   0.0  20.0  1.0    1.0   9600.0
1664496  38.0  6.0  14.0  5.0   0.0  32.0  1.0    8.0   2400.0
1664497  37.0  1.0  19.0  3.0  13.0  40.0  2.0    9.0  19700.0
1664498  47.0  1.0  16.0  1.0   1.0  40.0  1.0    8.0  18700.0
1664499  34.0  1.0  16.0  5.0   2.0  40.0  1.0    1.0   7900.0

[1664500 rows x 9 columns]

In [ ]:
df_full["SCHL_new"] = df_full["SCHL"].apply(lambda x: 1 if x <= 15 else (x - 14))
df_full["SCHL"] = df_full["SCHL_new"]
df_full.drop(columns=["SCHL_new"], inplace=True)

In [50]:
df_full.describe()

,AGEP,COW,SCHL,MAR,RELP,WKHP,SEX,RAC1P,PINCP
count,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06,1.664500e+06
mean,4.341127e+01,2.077500e+00,4.914338e+00,2.521997e+00,2.241254e+00,3.833390e+01,1.479282e+00,1.874745e+00,5.666386e+04
std,1.530203e+01,1.825338e+00,2.456141e+00,1.796720e+00,4.385288e+00,1.308073e+01,4.995707e-01,2.084384e+00,7.306745e+04
min,1.700000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.040000e+02
25%,3.000000e+01,1.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,3.500000e+01,1.000000e+00,1.000000e+00,2.000000e+04
50%,4.300000e+01,1.000000e+00,5.000000e+00,1.000000e+00,1.000000e+00,4.000000e+01,1.000000e+00,1.000000e+00,3.900000e+04
75%,5.600000e+01,3.000000e+00,7.000000e+00,5.000000e+00,2.000000e+00,4.400000e+01,2.000000e+00,1.000000e+00,6.800000e+04
max,9.600000e+01,8.000000e+00,1.000000e+01,5.000000e+00,1.700000e+01,9.900000e+01,2.000000e+00,9.000000e+00,1.423000e+06

In [ ]:
cat_features = ['COW', 'SCHL', 'MAR', 'RELP', 'SEX', 'RAC1P']
num_features = ['AGEP', 'WKHP']

In [52]:
df_full = pd.get_dummies(df_full, columns=cat_features, dtype=float)
df_full = scale_num_features(df_full, num_features=num_features)
df_full['PINCP'] = df_full['PINCP'].apply(lambda x: 1 if x >= 50000 else 0)

In [53]:
df_full

,AGEP,WKHP,PINCP,COW_1.0,COW_2.0,COW_3.0,COW_4.0,COW_5.0,COW_6.0,COW_7.0,...,SEX_2.0,RAC1P_1.0,RAC1P_2.0,RAC1P_3.0,RAC1P_4.0,RAC1P_5.0,RAC1P_6.0,RAC1P_7.0,RAC1P_8.0,RAC1P_9.0
0,-1.660647,-1.325148,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.626631,0.127371,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.157579,0.127371,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.660647,-2.777666,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.464595,0.891854,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1664495,-0.288280,-1.401596,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1664496,-0.353631,-0.484216,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1664497,-0.418982,0.127371,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1664498,0.234526,0.127371,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1664499,-0.615034,0.127371,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
y = df_full['PINCP']
X = df_full.drop(columns=['PINCP'])

In [80]:
y

0          0
1          0
2          0
3          0
4          0
          ..
1664495    0
1664496    0
1664497    0
1664498    0
1664499    0
Name: PINCP, Length: 1664500, dtype: int64

In [70]:
X, y = getACSIncomeData()

In [71]:
X

,AGEP,WKHP,COW_1.0,COW_2.0,COW_3.0,COW_4.0,COW_5.0,COW_6.0,COW_7.0,COW_8.0,...,SEX_2.0,RAC1P_1.0,RAC1P_2.0,RAC1P_3.0,RAC1P_4.0,RAC1P_5.0,RAC1P_6.0,RAC1P_7.0,RAC1P_8.0,RAC1P_9.0
0,-1.660647,-1.325148,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.626631,0.127371,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.157579,0.127371,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.660647,-2.777666,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.464595,0.891854,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1664495,-0.288280,-1.401596,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1664496,-0.353631,-0.484216,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1664497,-0.418982,0.127371,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1664498,0.234526,0.127371,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1664499,-0.615034,0.127371,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
data_set = IncomeDataset()
train_data, test_data = data_set.get_data(0)
X_train, y_train = train_data
X_test, y_test = test_data

In [54]:
base_model = LR()
base_model.train(X_train.values, y_train.values)

In [55]:
np.sum(np.abs(base_model.predict(X_train.values) - y_train.values)) / len(y_train)

np.float64(0.2271613097026134)

In [52]:
np.sum(np.abs(base_model.predict(X_test.values) - y_test.values)) / len(y_test)

np.float64(0.22728266746770803)

### NN

In [8]:
data_set = IncomeDataset()
train_data, test_data = data_set.get_data(0)
X_train, y_train = train_data
X_test, y_test = test_data

base_model = NN(X_train.shape[1])
base_model.train(X_train.values, y_train.values, verbose=1)

Epoch 0: train loss: 0.6906492710113525
Epoch 1: train loss: 0.6862571835517883
Epoch 2: train loss: 0.6821297407150269
Epoch 3: train loss: 0.6781940460205078
Epoch 4: train loss: 0.6743854284286499
Epoch 5: train loss: 0.6706457734107971
Epoch 6: train loss: 0.6669087409973145
Epoch 7: train loss: 0.6630986928939819
Epoch 8: train loss: 0.6591463088989258
Epoch 9: train loss: 0.6549786925315857
Epoch 10: train loss: 0.6505325436592102
Epoch 11: train loss: 0.6457536816596985
Epoch 12: train loss: 0.6405906677246094
Epoch 13: train loss: 0.634998619556427
Epoch 14: train loss: 0.6289404630661011
Epoch 15: train loss: 0.6223869323730469
Epoch 16: train loss: 0.6153113842010498
Epoch 17: train loss: 0.6077033877372742
Epoch 18: train loss: 0.599578320980072
Epoch 19: train loss: 0.5909833312034607
Epoch 20: train loss: 0.5820037722587585
Epoch 21: train loss: 0.572772204875946
Epoch 22: train loss: 0.5634620785713196
Epoch 23: train loss: 0.5542765259742737
Epoch 24: train loss: 0.5454128384590149
Epoch 25: train loss: 0.5370482206344604
Epoch 26: train loss: 0.5293306708335876
Epoch 27: train loss: 0.5223650336265564
Epoch 28: train loss: 0.5162006616592407
Epoch 29: train loss: 0.5108394026756287
Epoch 30: train loss: 0.5062482357025146
Epoch 31: train loss: 0.5023569464683533
Epoch 32: train loss: 0.49906429648399353
Epoch 33: train loss: 0.49624666571617126
Epoch 34: train loss: 0.4937715530395508
Epoch 35: train loss: 0.4915187358856201
Epoch 36: train loss: 0.4894028604030609
Epoch 37: train loss: 0.4873826205730438
Epoch 38: train loss: 0.4854544401168823
Epoch 39: train loss: 0.4836302697658539
Epoch 40: train loss: 0.48193132877349854
Epoch 41: train loss: 0.48036855459213257
Epoch 42: train loss: 0.4789351224899292
Epoch 43: train loss: 0.47760266065597534
Epoch 44: train loss: 0.47633081674575806
Epoch 45: train loss: 0.47508057951927185
Epoch 46: train loss: 0.4738292396068573
Epoch 47: train loss: 0.4725687801837921
Epoch 48: train loss: 0.4713072180747986
Epoch 49: train loss: 0.47006750106811523
Epoch 50: train loss: 0.46888667345046997
Epoch 51: train loss: 0.4678052067756653
Epoch 52: train loss: 0.46685558557510376
Epoch 53: train loss: 0.46605736017227173
Epoch 54: train loss: 0.4654073417186737
Epoch 55: train loss: 0.4648767411708832
Epoch 56: train loss: 0.46441909670829773
Epoch 57: train loss: 0.46398138999938965
Epoch 58: train loss: 0.4635166823863983
Epoch 59: train loss: 0.4629969298839569
Epoch 60: train loss: 0.46241864562034607
Epoch 61: train loss: 0.4618028998374939
Epoch 62: train loss: 0.4611814022064209
Epoch 63: train loss: 0.46058881282806396
Epoch 64: train loss: 0.4600546061992645
Epoch 65: train loss: 0.45959237217903137
Epoch 66: train loss: 0.45919719338417053
Epoch 67: train loss: 0.4588499069213867
Epoch 68: train loss: 0.4585234224796295
Epoch 69: train loss: 0.4581918716430664
Epoch 70: train loss: 0.45784011483192444
Epoch 71: train loss: 0.45746663212776184
Epoch 72: train loss: 0.4570804238319397
Epoch 73: train loss: 0.45669645071029663
Epoch 74: train loss: 0.45632636547088623
Epoch 75: train loss: 0.4559764564037323
Epoch 76: train loss: 0.4556453824043274
Epoch 77: train loss: 0.455327570438385
Epoch 78: train loss: 0.4550175368785858
Epoch 79: train loss: 0.45471304655075073
Epoch 80: train loss: 0.45441514253616333
Epoch 81: train loss: 0.45412546396255493
Epoch 82: train loss: 0.45384472608566284
Epoch 83: train loss: 0.4535709619522095
Epoch 84: train loss: 0.4533015787601471
Epoch 85: train loss: 0.45303618907928467
Epoch 86: train loss: 0.4527777135372162
Epoch 87: train loss: 0.4525300860404968
Epoch 88: train loss: 0.4522955119609833
Epoch 89: train loss: 0.4520733654499054
Epoch 90: train loss: 0.4518600106239319
Epoch 91: train loss: 0.4516505002975464
Epoch 92: train loss: 0.4514429569244385
Epoch 93: train loss: 0.4512379467487335
Epoch 94: train loss: 0.45103806257247925
Epoch 95: train loss: 0.45084482431411743
Epoch 96: train loss: 0.4506584107875824
Epoch 97: train loss: 0.45047813653945923
Epoch 98: train loss: 0.4503025710582733
Epoch 99: train loss: 0.45013242959976196

In [9]:
np.sum(np.abs(base_model.predict(X_train.values) - y_train.values)) / len(y_train)

np.float64(0.21944848302793632)

In [10]:
np.sum(np.abs(base_model.predict(X_test.values) - y_test.values)) / len(y_test)

np.float64(0.22087834184439772)

In [ ]:
# torch.save(base_model.model.state_dict(), "../results/recourse_model/income_0.pth")

In [15]:
data_set = IncomeDataset()
train_data, test_data = data_set.get_data(1)
X_train, y_train = train_data
X_test, y_test = test_data

base_model = NN(X_train.shape[1])
base_model.train(X_train.values, y_train.values, verbose=1)

Epoch 0: train loss: 0.6906533241271973
Epoch 1: train loss: 0.6862615942955017
Epoch 2: train loss: 0.6821350455284119
Epoch 3: train loss: 0.678200364112854
Epoch 4: train loss: 0.6743934154510498
Epoch 5: train loss: 0.6706556677818298
Epoch 6: train loss: 0.6669219136238098
Epoch 7: train loss: 0.6631178855895996
Epoch 8: train loss: 0.6591777801513672
Epoch 9: train loss: 0.6550331115722656
Epoch 10: train loss: 0.650622546672821
Epoch 11: train loss: 0.6458896994590759
Epoch 12: train loss: 0.6407774686813354
Epoch 13: train loss: 0.6352354884147644
Epoch 14: train loss: 0.6292197108268738
Epoch 15: train loss: 0.6226962804794312
Epoch 16: train loss: 0.6156388521194458
Epoch 17: train loss: 0.6080406904220581
Epoch 18: train loss: 0.5999251008033752
Epoch 19: train loss: 0.5913422107696533
Epoch 20: train loss: 0.5823779106140137
Epoch 21: train loss: 0.5731605291366577
Epoch 22: train loss: 0.5638589262962341
Epoch 23: train loss: 0.5546765327453613
Epoch 24: train loss: 0.5458187460899353
Epoch 25: train loss: 0.5374786257743835
Epoch 26: train loss: 0.5298202633857727
Epoch 27: train loss: 0.5229607820510864
Epoch 28: train loss: 0.5169410705566406
Epoch 29: train loss: 0.511738121509552
Epoch 30: train loss: 0.507300853729248
Epoch 31: train loss: 0.5035451054573059
Epoch 32: train loss: 0.500358521938324
Epoch 33: train loss: 0.4976201057434082
Epoch 34: train loss: 0.49520012736320496
Epoch 35: train loss: 0.4929836392402649
Epoch 36: train loss: 0.4908914864063263
Epoch 37: train loss: 0.488884299993515
Epoch 38: train loss: 0.48696368932724
Epoch 39: train loss: 0.485145628452301
Epoch 40: train loss: 0.4834505021572113
Epoch 41: train loss: 0.48189106583595276
Epoch 42: train loss: 0.4804643988609314
Epoch 43: train loss: 0.47914770245552063
Epoch 44: train loss: 0.4778970777988434
Epoch 45: train loss: 0.4766731858253479
Epoch 46: train loss: 0.4754498302936554
Epoch 47: train loss: 0.4742191433906555
Epoch 48: train loss: 0.47298574447631836
Epoch 49: train loss: 0.47177252173423767
Epoch 50: train loss: 0.47061580419540405
Epoch 51: train loss: 0.4695562720298767
Epoch 52: train loss: 0.4686250686645508
Epoch 53: train loss: 0.4678390622138977
Epoch 54: train loss: 0.4671950340270996
Epoch 55: train loss: 0.4666665196418762
Epoch 56: train loss: 0.4662081003189087
Epoch 57: train loss: 0.4657679796218872
Epoch 58: train loss: 0.46530279517173767
Epoch 59: train loss: 0.4647883474826813
Epoch 60: train loss: 0.4642232358455658
Epoch 61: train loss: 0.46362748742103577
Epoch 62: train loss: 0.46303224563598633
Epoch 63: train loss: 0.46246910095214844
Epoch 64: train loss: 0.46196356415748596
Epoch 65: train loss: 0.4615253210067749
Epoch 66: train loss: 0.4611475169658661
Epoch 67: train loss: 0.4608100354671478
Epoch 68: train loss: 0.4604862928390503
Epoch 69: train loss: 0.46015313267707825
Epoch 70: train loss: 0.45979949831962585
Epoch 71: train loss: 0.4594264030456543
Epoch 72: train loss: 0.45904508233070374
Epoch 73: train loss: 0.4586697518825531
Epoch 74: train loss: 0.45831215381622314
Epoch 75: train loss: 0.45797574520111084
Epoch 76: train loss: 0.4576556086540222
Epoch 77: train loss: 0.4573439359664917
Epoch 78: train loss: 0.4570350646972656
Epoch 79: train loss: 0.4567283093929291
Epoch 80: train loss: 0.45642784237861633
Epoch 81: train loss: 0.45613786578178406
Epoch 82: train loss: 0.4558616578578949
Epoch 83: train loss: 0.45559796690940857
Epoch 84: train loss: 0.4553431272506714
Epoch 85: train loss: 0.4550939202308655
Epoch 86: train loss: 0.45485007762908936
Epoch 87: train loss: 0.4546149671077728
Epoch 88: train loss: 0.4543911814689636
Epoch 89: train loss: 0.4541792571544647
Epoch 90: train loss: 0.4539772868156433
Epoch 91: train loss: 0.453781396150589
Epoch 92: train loss: 0.4535881578922272
Epoch 93: train loss: 0.453397274017334
Epoch 94: train loss: 0.4532099664211273
Epoch 95: train loss: 0.45302942395210266
Epoch 96: train loss: 0.4528566896915436
Epoch 97: train loss: 0.4526907801628113
Epoch 98: train loss: 0.45252957940101624
Epoch 99: train loss: 0.4523719549179077

In [16]:
np.sum(np.abs(base_model.predict(X_train.values) - y_train.values)) / len(y_train)

np.float64(0.2207990387503755)

In [17]:
np.sum(np.abs(base_model.predict(X_test.values) - y_test.values)) / len(y_test)

np.float64(0.2197644938419946)

In [ ]:
# torch.save(base_model.model.state_dict(), "../results/recourse_model/income_1.pth")

### Folktables

In [11]:
data_set = SBADataset()
train_data, test_data = data_set.get_data(1)
X_train, y_train = train_data
X_test, y_test = test_data

In [13]:
X_test

,Zip,NAICS,ApprovalDate,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,...,GrAppv,SBA_Appv,Portion,daysterm,xx,RevLineCr_-1,RevLineCr_0,RevLineCr_N,RevLineCr_T,RevLineCr_Y
1609,1.027917,-1.012018,0.468049,0.354715,0.904285,-0.203553,-0.376699,0.147856,-0.265297,-0.192770,...,1.957623,2.479424,1.631627,0.904285,1.036093,0.0,0.0,1.0,0.0,0.0
1197,1.393135,-1.176647,-0.174351,-0.159500,1.502553,0.853652,-0.376699,-0.313113,-0.265297,-0.192770,...,-0.388851,-0.395990,0.232805,1.502553,1.301532,0.0,0.0,1.0,0.0,0.0
1654,-0.596500,-1.012018,0.543171,0.611822,-0.651213,-0.111622,-0.376699,-0.082628,0.068014,-0.192770,...,-0.723217,-0.716059,-1.166017,-0.651213,-0.378053,0.0,0.0,0.0,0.0,1.0
1288,1.008579,0.853786,-2.351492,-2.473464,-0.292252,-0.088639,2.613674,-0.313113,-0.265297,6.772448,...,-0.316948,-0.274711,0.792334,-0.292252,-1.218913,0.0,0.0,1.0,0.0,0.0
1677,-1.258975,1.184875,0.571254,0.611822,-0.651213,-0.249518,-0.376699,-0.313113,-0.181969,-0.192770,...,-0.782396,-0.750754,-1.166017,-0.651213,-0.359747,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1715,-0.515832,0.817202,0.600742,0.611822,-0.292252,-0.226535,-0.376699,-0.313113,-0.265297,-0.192770,...,-0.590062,-0.546917,0.792334,-0.292252,-0.011626,0.0,0.0,1.0,0.0,0.0
411,-0.745129,0.636109,-0.871514,-0.930821,1.502553,-0.180570,-0.376699,-0.313113,-0.265297,-0.192770,...,-0.279369,-0.299709,0.232805,1.502553,0.985751,0.0,1.0,0.0,0.0,0.0
1927,1.644533,0.853786,-1.556741,-1.445035,-0.830693,-0.203553,2.613674,-0.313113,-0.265297,-0.192770,...,-0.702504,-0.665403,0.512569,-0.830693,-1.434315,0.0,0.0,1.0,0.0,0.0
1833,1.345066,0.853786,-1.805276,-1.702142,-1.010174,-0.226535,-0.376699,-0.313113,-0.265297,-0.192770,...,-0.678832,-0.627584,1.072098,-1.010174,-1.683278,0.0,0.0,1.0,0.0,0.0
2052,0.728450,0.853786,-1.374201,-1.445035,-0.292252,-0.203553,-0.376699,-0.313113,-0.265297,-0.192770,...,-0.303041,-0.320527,0.232805,-0.292252,-0.856453,0.0,1.0,0.0,0.0,0.0

In [3]:
from folktables import ACSDataSource, ACSIncome

In [ ]:
datasource = ACSDataSource(survey_year='2018', horizon='1-Year', survey='person')
ca_data = datasource.get_data(states=['CA'], download=False)

Downloading data for 2018 1-Year person survey for CA...

In [12]:
ca_features, ca_labels, _ = ACSIncome.df_to_pandas(ca_data)