In [1]:
import sys
sys.path.append("..")

In [2]:
import tqdm
import torch
import pickle
import warnings
import numpy as np
import pandas as pd
import torch.optim as optim
from copy import deepcopy
import plotly.express as px
import plotly.graph_objects as go

from src.data import *
from src.utils import *
from src.model import *
from src.recourse import *

warnings.filterwarnings('ignore')

In [3]:
def append_result(d, objective, loss, cost, m1_validity, wc_validity, m1_expectation, wc_expectation):
    d['cost'].append(cost)
    d['m1_validity'].append(m1_validity)
    d['wc_validity'].append(wc_validity)
    d['m1_probability'].append(m1_expectation)
    d['wc_probability'].append(wc_expectation)
    d['loss'].append(loss)
    d['J'].append(objective) 
    
def get_result(d, algorithm, seed, alpha, lamb, theta_0, theta_r):
    result = {
        'algorithm': algorithm, 
        'seed': seed,
        'alpha': alpha,
        'lambda': lamb,
        'theta_0': theta_0,
        'theta_r': theta_r
        }
    
    for key in d.keys():
        result[key] = np.mean(d[key])
    return result

In [4]:
def get_theta_adv_linf(X_0, X_r, theta_0, alpha, lamb):
    
    theta_adv = deepcopy(theta_0)
    
    for i in range(theta_0.shape[0]):
        theta_r_min = deepcopy(theta_0)
        theta_r_max = deepcopy(theta_0)
        
        theta_r_min[i] -= alpha
        theta_r_max[i] += alpha
        weights_r_min, bias_r_min = theta_r_min[:-1], theta_r_min[[-1]]
        weights_r_max, bias_r_max = theta_r_max[:-1], theta_r_max[[-1]]
        J_min, J_max = [], []
        for xi in range(len(X_r)):
            x_0 = X_0[xi]
            x_r = X_r[xi]
            J = RecourseCost(x_0, lamb)
            j_min = J.eval(x_r, weights_r_min, bias_r_min)
            j_max = J.eval(x_r, weights_r_max, bias_r_max)
            J_min.append(j_min)
            J_max.append(j_max)
        
        
        if np.mean(J_min) > np.mean(J_max):
            theta_adv[i] -= alpha
        else:
            theta_adv[i] += alpha

    return theta_adv

In [5]:
def get_theta_adv_l1(X_0, X_r, theta_0, alpha, lamb):
    thetas = generateThetas(theta_0, alpha)
    if alpha == 0:
        return thetas[0].copy()
    
    Js = np.empty((X_0.shape[0], thetas.shape[0]))
    for i in range(X_0.shape[0]):
         J = RecourseCost(X_0[i], lamb)
         for j, theta in enumerate(thetas):  
            Js[i, j] = J.eval(X_r[i], theta[:-1], np.array([theta[-1]]))
    
    Js_sum = Js.sum(axis=0) 
    Js_sum_maxI = np.argmax(Js_sum)
    theta_adv = thetas[Js_sum_maxI]

    return theta_adv

def generateThetas(theta0 : np.ndarray, alpha):
        # theta0 has bias
        thetas = theta0.copy()
        if alpha == 0:
            return np.array([thetas])
        
        thetas = np.repeat(thetas.reshape(1, theta0.size), (theta0.size * 2) - 1, axis=0)
        thetas_i = 0

        for i in range(theta0.size):
            if i == theta0.size - 1:
                thetas[thetas_i][i] -= alpha
                thetas_i += 1
                break

            thetas[thetas_i][i] += alpha
            thetas_i += 1
            thetas[thetas_i][i] -= alpha
            thetas_i += 1

        return thetas

In [6]:
def calThetaAdv_l1(xP: np.ndarray, theta0: np.ndarray, alpha):
    # xP has bias
    thetaP = theta0.copy()
    i = np.argmax(np.abs(xP))
    thetaP[i] -= (alpha * np.sign(xP[i]))

    return thetaP

def calThetaAdv_linf(xP: np.ndarray, weights: np.ndarray, bias, alpha):
    # xP does not have bias
    weights_adv = weights - (alpha * np.sign(xP))

    for i in range(len(xP)):
        if np.sign(xP[i]) == 0:
            weights_adv[i] = weights_adv[i] - (alpha * np.sign(weights_adv[i]))
    bias_adv = bias - alpha

    return np.concat((weights_adv, bias_adv))

def calTheta(xP: np.array, weights: np.array, bias: np.array, alpha: float, methods: str):
    if methods == "L-inf":
        thetaP = calThetaAdv_linf(xP, weights, bias, alpha)
    else:
        thetaP = calThetaAdv_l1(np.hstack((xP, np.array([1]))), np.hstack((weights, bias)), alpha)

    return thetaP[:-1], np.array([thetaP[-1]])

In [7]:
def evaluate_performance_each(X_0, X_r, theta_0, alpha, lamb, seed, algorithm, theta_adv_method='L-inf'):
    results = {'cost': [], 'm1_validity': [], 'wc_validity': [], 'm1_probability': [], 'wc_probability': [], 'loss': [], 'J': []}
    
    n = len(X_r)
    Y_0 = np.hstack((np.ones((n//2,)), np.zeros((n - n//2,))))
    
    clf = LR()
    clf.train(X_0, Y_0)
    clf_adv = deepcopy(clf)


    for i in tqdm.trange(n, desc=f'[] [] [{algorithm.capitalize()}] [ seed={seed} ] [ α={alpha} ] [ λ={lamb} ]', colour='#0091ff'):
        x_0 = X_0[i]
        x_r = X_r[i]
        t_0 = theta_0[i]
        w_0, b_0 = t_0[:-1], t_0[[-1]]
        if alpha != 0:
            w_0_adv, b_0_adv = calTheta(x_r, w_0, b_0, alpha, theta_adv_method)
        else:
            w_0_adv, b_0_adv = w_0.copy(), b_0.copy()

        clf.model.coef_ = w_0.reshape(1,-1)
        clf.model.intercept_ = b_0
        clf_adv.model.coef_ = w_0_adv.reshape(1,-1)
        clf_adv.model.intercept_ = b_0_adv

        J = RecourseCost(x_0, lamb)
        bce_loss, cost, price = J.eval(x_r, w_0_adv, b_0_adv, True)

        m1_validity = clf.predict(x_r.reshape(1,-1))[0]
        m1_probability = clf.predict_proba(x_r.reshape(1,-1))[0,1]
        
        wc_validity = clf_adv.predict(x_r.reshape(1,-1))[0]
        wc_probability = clf_adv.predict_proba(x_r.reshape(1,-1))[0,1]
        
        append_result(results, price, bce_loss, cost, m1_validity, wc_validity, m1_probability, wc_probability)
        
    return get_result(results, algorithm, seed, alpha, lamb, None, None)

In [8]:
def runCostValidityTradeoff (results: dict, params: dict):
    for model in params['base_model']:
        for dataset in params['data']:
            model_dataset_name = model + '_' + dataset

            for algorithm in params['algorithms']:
                for seed in params['seeds']:
                    for v_alpha in params['alphas'][algorithm]:
                        for v_lamb in params['lambdas'][model_dataset_name][algorithm]:
                            data = pd.read_pickle(f"../results/recourse/{model}_{dataset}_{algorithm}_{v_lamb}_{v_alpha}_{seed}.pkl")
                            alpha = data["alpha"].unique().item()
                            lamb = data["lambda"].unique().item()
                            X_0 = np.stack(data["x_0"])
                            X_r = np.stack(data["x_r"])
                            theta_0 = np.stack(data["theta_0"])

                            if params['include_mask'] and algorithm != "L1PSD":
                                data_l1psd = pd.read_pickle(f"../results/recourse/{model}_{dataset}_L1PSD_0.1_0.1_{seed}.pkl")
                                mask_i = data_l1psd["i"].to_numpy()
                                X_0 = X_0[mask_i]
                                X_r = X_r[mask_i]
                                theta_0 = theta_0[mask_i]
                            
                            res = evaluate_performance_each(X_0, X_r, theta_0, alpha, lamb, seed, algorithm, theta_adv_method="L-1" if "L1" in algorithm else "L-inf")
                            
                            results['model'].append(model)
                            results['dataset'].append(dataset)
                            results['algorithm'].append(algorithm)
                            results['seed'].append(seed)
                            results['alpha'].append(alpha)
                            results['lambda'].append(lamb)
                            results['Cost'].append(res['cost'])
                            results['Current Validity'].append(res['m1_probability'])
                            results['Worst Case Validity'].append(res['wc_probability'])
                            results['BCE Loss'].append(res['loss'])
                            results['J'].append(res['J'])
    
    df_results = pd.DataFrame(results)
    return df_results

In [29]:
params = {}
# 'lr', 'nn'
params['base_model'] = ['lr', 'nn']
# 'synthetic', 'german', 'sba'
params['data'] = ['german', 'sba']
params['seeds'] = range(5)
# 'Alg1', 'L1PSD', 'ROARLInf', 'ROARL1'
params['algorithms'] = ['Alg1', 'L1PSD', 'ROARLInf', 'ROARL1']
# 'ONE', 'MANY', 'LARGESTALPHA', 'SMALLESTALPHA', 'THETA0'
params['adv_method'] = 'ONE'
params['include_base_model'] = False
params['include_mask'] = True

params['alphas'] = {params['algorithms'][0] : [0.1],
            params['algorithms'][1] : [0.1], 
            params['algorithms'][2] : [0.1], 
            params['algorithms'][3] : [0.1]}

params['lambdas'] = dict()
# lr_german
params['lambdas']['lr_german'] = {params['algorithms'][0] : np.hstack((np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,0.55, 0.1))).round(5),
            params['algorithms'][1] : [0.5,0.3,0.1,0.04,0.01,0.004,0.001], 
            params['algorithms'][2] : np.hstack((np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,0.55, 0.1), np.array([0.0001, 0.00001]))).round(7), 
            params['algorithms'][3] : np.hstack((np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,0.55, 0.1), np.array([0.0001, 0.00001]))).round(7)}
# params['lambdas']['lr_german'] = {params['algorithms'][0] : [0.1],
#             params['algorithms'][1] : [0.1], 
#             params['algorithms'][2] : [0.1], 
#             params['algorithms'][3] : [0.1]}

# nn_german
params['lambdas']['nn_german'] = {params['algorithms'][0] : np.hstack((np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,1.05, 0.1), np.array([2.0, 3.0, 4.0, 5.0]))).round(5),
            params['algorithms'][1] : [3.0, 0.7, 0.3, 0.1, 0.05, 0.01, 0.001], 
            params['algorithms'][2] : np.hstack((np.array([1e-7,1e-6,1e-5,1e-4]),np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,1.05, 0.1))).round(9), 
            params['algorithms'][3] : np.hstack((np.array([1e-7,1e-6,1e-5,1e-4]),np.arange(0.001,0.0105,0.001),np.arange(0.02, 0.105, 0.01),np.arange(0.2,1.05, 0.1))).round(9)}
# params['lambdas']['nn_german'] = {params['algorithms'][0] : [0.3],
#             params['algorithms'][1] : [0.3], 
#             params['algorithms'][2] : [0.3], 
#             params['algorithms'][3] : [0.3]}

# lr_sba
params['lambdas']['lr_sba'] = {params['algorithms'][0] : [0.001, 0.01, 0.1, 0.7, 1.4, 2.1, 2.3, 2.6, 2.8, 3.0, 3.1, 3.3, 3.5],
            params['algorithms'][1] : [0.001, 0.01, 0.1, 0.7, 1.4, 2.1, 2.8, 3.0, 3.5], 
            params['algorithms'][2] : [0.001, 0.01, 0.08, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.1, 1.4, 1.5, 1.6, 1.8, 2, 2.1, 2.8, 3.5], 
            params['algorithms'][3] : [0.001, 0.01, 0.08,0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.1, 1.4, 1.5, 1.6, 1.8, 2, 2.1, 2.8, 3.5]}
# params['lambdas']['lr_sba'] = {params['algorithms'][0] : [0.7],
#             params['algorithms'][1] : [0.7], 
#             params['algorithms'][2] : [0.7], 
#             params['algorithms'][3] : [0.7]}

# nn_sba
params['lambdas']['nn_sba'] = {params['algorithms'][0] :[0.00001, 0.0001, 0.001, 0.01, 0.1, 0.7, 1.4, 2.1, 2.8, 3.5],
            params['algorithms'][1] : [0.001, 0.01, 0.1, 0.7, 1.4, 2.1, 2.8, 3.5], 
            params['algorithms'][2] : [0.001, 0.01, 0.1, 0.3, 0.5, 0.7, 1.4, 1.7, 1.9, 2.1, 2.8, 3.5], 
            params['algorithms'][3] : [0.001, 0.01, 0.1, 0.3, 0.5, 0.7, 1.4, 1.7, 1.9, 2.1, 2.8, 3.5]}
# params['lambdas']['nn_sba'] = {params['algorithms'][0] : [0.7],
#             params['algorithms'][1] : [0.7], 
#             params['algorithms'][2] : [0.7], 
#             params['algorithms'][3] : [0.7]}

results = {
    'model': [],
    'dataset': [],
    'algorithm': [],
    'seed': [],
    'alpha': [],
    'lambda': [],
    'Cost': [],
    'Current Validity': [],
    'Worst Case Validity': [],
    'BCE Loss': [],
    'J': []
}

df_results = runCostValidityTradeoff(results, params)

[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.001 ]:   0%|          | 0/16 [00:00<?, ?it/s]

[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 16/16 [00:00<00:00, 2085.49it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 16/16 [00:00<00:00, 1849.85it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 16/16 [00:00<00:00, 2167.11it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 16/16 [00:00<00:00, 2405.68it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 16/16 [00:00<00:00, 2180.77it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 16/16 [00:00<00:00, 1633.77it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 16/16 [00:00<00:00, 1553.05it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 16/16 [00:00<00:00, 2219.21it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 16/16 [00:00<00:00, 1723.44it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 16/16 [00:00<00:00, 2277.58it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 16/16 [00:00<00:00, 2496.15it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 16/16 [00:00<00:00, 2583.89it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 16/16 [00:00<00:00, 2547.12it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 16/16 [00:00<00:00, 2491.33it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 16/16 [00:00<00:00, 2239.35it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 16/16 [00:00<00:00, 2343.43it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 16/16 [00:00<00:00, 2555.65it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 16/16 [00:00<00:00, 2509.68it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 16/16 [00:00<00:00, 2567.78it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 16/16 [00:00<00:00, 2312.74it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 16/16 [00:00<00:00, 2190.88it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 16/16 [00:00<00:00, 2460.99it/s]
[] [] [Alg1] [ seed=0 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 16/16 [00:00<00:00, 2483.21it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 12/12 [00:00<00:00, 2321.25it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 12/12 [00:00<00:00, 2397.43it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 12/12 [00:00<00:00, 2323.93it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 12/12 [00:00<00:00, 2402.58it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 12/12 [00:00<00:00, 2459.64it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 12/12 [00:00<00:00, 2219.70it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 12/12 [00:00<00:00, 2438.55it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 12/12 [00:00<00:00, 1461.35it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 12/12 [00:00<00:00, 1733.72it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 12/12 [00:00<00:00, 2165.92it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 12/12 [00:00<00:00, 2335.03it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 12/12 [00:00<00:00, 2424.92it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 12/12 [00:00<00:00, 2152.49it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 12/12 [00:00<00:00, 1872.53it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 12/12 [00:00<00:00, 2200.58it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 12/12 [00:00<00:00, 1830.24it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 12/12 [00:00<00:00, 1902.54it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 12/12 [00:00<00:00, 2221.66it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 12/12 [00:00<00:00, 1465.86it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 12/12 [00:00<00:00, 1517.16it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 12/12 [00:00<00:00, 1810.43it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 12/12 [00:00<00:00, 2264.34it/s]
[] [] [Alg1] [ seed=1 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 12/12 [00:00<00:00, 2352.06it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 11/11 [00:00<00:00, 2173.93it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 11/11 [00:00<00:00, 1557.38it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 11/11 [00:00<00:00, 1929.95it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 11/11 [00:00<00:00, 2393.51it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 11/11 [00:00<00:00, 2332.76it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 11/11 [00:00<00:00, 1659.68it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 11/11 [00:00<00:00, 1935.21it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 11/11 [00:00<00:00, 2477.44it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 11/11 [00:00<00:00, 1989.45it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 11/11 [00:00<00:00, 2445.79it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 11/11 [00:00<00:00, 2186.29it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 11/11 [00:00<00:00, 2320.91it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 11/11 [00:00<00:00, 2173.83it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 11/11 [00:00<00:00, 2305.60it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 11/11 [00:00<00:00, 2094.49it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 11/11 [00:00<00:00, 1989.88it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 11/11 [00:00<00:00, 2257.43it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 11/11 [00:00<00:00, 2194.40it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 11/11 [00:00<00:00, 2201.42it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 11/11 [00:00<00:00, 2311.72it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 11/11 [00:00<00:00, 1881.62it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 11/11 [00:00<00:00, 2185.05it/s]
[] [] [Alg1] [ seed=2 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 11/11 [00:00<00:00, 2435.33it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 15/15 [00:00<00:00, 2261.73it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 15/15 [00:00<00:00, 2328.36it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 15/15 [00:00<00:00, 2396.75it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 15/15 [00:00<00:00, 2224.54it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 15/15 [00:00<00:00, 2301.36it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 15/15 [00:00<00:00, 2011.66it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 15/15 [00:00<00:00, 2342.92it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 15/15 [00:00<00:00, 2394.56it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 15/15 [00:00<00:00, 2302.79it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 15/15 [00:00<00:00, 2082.02it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 15/15 [00:00<00:00, 2329.39it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 15/15 [00:00<00:00, 2409.60it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 15/15 [00:00<00:00, 1962.58it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 15/15 [00:00<00:00, 1509.65it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 15/15 [00:00<00:00, 1813.05it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 15/15 [00:00<00:00, 1929.24it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 15/15 [00:00<00:00, 2007.42it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 15/15 [00:00<00:00, 1581.60it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 15/15 [00:00<00:00, 1609.73it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 15/15 [00:00<00:00, 1994.82it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 15/15 [00:00<00:00, 2108.82it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 15/15 [00:00<00:00, 1670.46it/s]
[] [] [Alg1] [ seed=3 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 15/15 [00:00<00:00, 2025.71it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 14/14 [00:00<00:00, 1804.17it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 14/14 [00:00<00:00, 1729.00it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 14/14 [00:00<00:00, 2129.40it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 14/14 [00:00<00:00, 1502.22it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 14/14 [00:00<00:00, 2181.13it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 14/14 [00:00<00:00, 1935.09it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 14/14 [00:00<00:00, 2110.95it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 14/14 [00:00<00:00, 2069.66it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 14/14 [00:00<00:00, 1966.65it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 14/14 [00:00<00:00, 2311.18it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 14/14 [00:00<00:00, 1901.75it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 14/14 [00:00<00:00, 2142.45it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 14/14 [00:00<00:00, 1956.17it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 14/14 [00:00<00:00, 1604.16it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 14/14 [00:00<00:00, 2241.92it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 14/14 [00:00<00:00, 2150.61it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 14/14 [00:00<00:00, 2049.07it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 14/14 [00:00<00:00, 2103.84it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 14/14 [00:00<00:00, 1987.42it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 14/14 [00:00<00:00, 1530.53it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 14/14 [00:00<00:00, 1927.09it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 14/14 [00:00<00:00, 1744.51it/s]
[] [] [Alg1] [ seed=4 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 14/14 [00:00<00:00, 1623.90it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 16/16 [00:00<00:00, 2060.45it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 16/16 [00:00<00:00, 2233.24it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 16/16 [00:00<00:00, 2499.40it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 16/16 [00:00<00:00, 2434.83it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 16/16 [00:00<00:00, 2232.20it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 16/16 [00:00<00:00, 2130.71it/s]
[] [] [L1psd] [ seed=0 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 16/16 [00:00<00:00, 2374.02it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 12/12 [00:00<00:00, 1962.17it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 12/12 [00:00<00:00, 2343.40it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 12/12 [00:00<00:00, 2298.04it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 12/12 [00:00<00:00, 1913.31it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 12/12 [00:00<00:00, 2003.33it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 12/12 [00:00<00:00, 1990.10it/s]
[] [] [L1psd] [ seed=1 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 12/12 [00:00<00:00, 2432.07it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 11/11 [00:00<00:00, 2332.17it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 11/11 [00:00<00:00, 2096.01it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 11/11 [00:00<00:00, 2597.38it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 11/11 [00:00<00:00, 2038.86it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 11/11 [00:00<00:00, 1899.67it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 11/11 [00:00<00:00, 2118.14it/s]
[] [] [L1psd] [ seed=2 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 11/11 [00:00<00:00, 1936.43it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 15/15 [00:00<00:00, 1998.87it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 15/15 [00:00<00:00, 1639.51it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 15/15 [00:00<00:00, 1569.02it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 15/15 [00:00<00:00, 2146.08it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 15/15 [00:00<00:00, 1913.98it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 15/15 [00:00<00:00, 1277.35it/s]
[] [] [L1psd] [ seed=3 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 15/15 [00:00<00:00, 2116.13it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 14/14 [00:00<00:00, 1770.60it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 14/14 [00:00<00:00, 2292.24it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 14/14 [00:00<00:00, 2149.04it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 14/14 [00:00<00:00, 2125.93it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 14/14 [00:00<00:00, 2388.26it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 14/14 [00:00<00:00, 2278.19it/s]
[] [] [L1psd] [ seed=4 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 14/14 [00:00<00:00, 2262.47it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 16/16 [00:00<00:00, 2187.52it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 16/16 [00:00<00:00, 2195.40it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 16/16 [00:00<00:00, 2476.98it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 16/16 [00:00<00:00, 2499.21it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 16/16 [00:00<00:00, 2336.90it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 16/16 [00:00<00:00, 1875.13it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 16/16 [00:00<00:00, 2377.81it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 16/16 [00:00<00:00, 2336.01it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 16/16 [00:00<00:00, 1904.34it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 16/16 [00:00<00:00, 2321.22it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 16/16 [00:00<00:00, 2492.07it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 16/16 [00:00<00:00, 2547.70it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 16/16 [00:00<00:00, 2481.74it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 16/16 [00:00<00:00, 2086.78it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 16/16 [00:00<00:00, 2248.13it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 16/16 [00:00<00:00, 2403.78it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 16/16 [00:00<00:00, 2139.13it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 16/16 [00:00<00:00, 2281.53it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 16/16 [00:00<00:00, 2057.92it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 16/16 [00:00<00:00, 2490.03it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 16/16 [00:00<00:00, 2221.93it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 16/16 [00:00<00:00, 2227.24it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 16/16 [00:00<00:00, 2305.35it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=0.0001 ]: 100%|██████████| 16/16 [00:00<00:00, 2510.53it/s]
[] [] [Roarlinf] [ seed=0 ] [ α=0.1 ] [ λ=1e-05 ]: 100%|██████████| 16/16 [00:00<00:00, 1623.81it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 12/12 [00:00<00:00, 1464.45it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 12/12 [00:00<00:00, 2026.48it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 12/12 [00:00<00:00, 2217.94it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 12/12 [00:00<00:00, 2247.45it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 12/12 [00:00<00:00, 2325.22it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.006 ]: 100%|██████████| 12/12 [00:00<00:00, 2268.01it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.007 ]: 100%|██████████| 12/12 [00:00<00:00, 2322.11it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.008 ]: 100%|██████████| 12/12 [00:00<00:00, 2156.92it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.009 ]: 100%|██████████| 12/12 [00:00<00:00, 2414.80it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.01 ]: 100%|██████████| 12/12 [00:00<00:00, 2043.51it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.02 ]: 100%|██████████| 12/12 [00:00<00:00, 2153.04it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.03 ]: 100%|██████████| 12/12 [00:00<00:00, 1526.13it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.04 ]: 100%|██████████| 12/12 [00:00<00:00, 2332.00it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.05 ]: 100%|██████████| 12/12 [00:00<00:00, 2426.32it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.06 ]: 100%|██████████| 12/12 [00:00<00:00, 2095.58it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.07 ]: 100%|██████████| 12/12 [00:00<00:00, 2270.57it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.08 ]: 100%|██████████| 12/12 [00:00<00:00, 1889.04it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.09 ]: 100%|██████████| 12/12 [00:00<00:00, 2166.76it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.1 ]: 100%|██████████| 12/12 [00:00<00:00, 1555.08it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.2 ]: 100%|██████████| 12/12 [00:00<00:00, 2286.76it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.3 ]: 100%|██████████| 12/12 [00:00<00:00, 1595.85it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.4 ]: 100%|██████████| 12/12 [00:00<00:00, 1391.11it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.5 ]: 100%|██████████| 12/12 [00:00<00:00, 1893.16it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=0.0001 ]: 100%|██████████| 12/12 [00:00<00:00, 2204.34it/s]
[] [] [Roarlinf] [ seed=1 ] [ α=0.1 ] [ λ=1e-05 ]: 100%|██████████| 12/12 [00:00<00:00, 2226.67it/s]
[] [] [Roarlinf] [ seed=2 ] [ α=0.1 ] [ λ=0.001 ]: 100%|██████████| 11/11 [00:00<00:00, 1813.00it/s]
[] [] [Roarlinf] [ seed=2 ] [ α=0.1 ] [ λ=0.002 ]: 100%|██████████| 11/11 [00:00<00:00, 2130.46it/s]
[] [] [Roarlinf] [ seed=2 ] [ α=0.1 ] [ λ=0.003 ]: 100%|██████████| 11/11 [00:00<00:00, 2317.76it/s]
[] [] [Roarlinf] [ seed=2 ] [ α=0.1 ] [ λ=0.004 ]: 100%|██████████| 11/11 [00:00<00:00, 2383.87it/s]
[] [] [Roarlinf] [ seed=2 ] [ α=0.1 ] [ λ=0.005 ]: 100%|██████████| 11/11 [00:00<00:00, 2319.04it/s]

In [15]:
df_results_sampled = df_results[df_results['lambda'].isin([0.1,0.01, 0.01])]
df_results_sampled

,model,dataset,algorithm,seed,alpha,lambda,Cost,Current Validity,Worst Case Validity,BCE Loss,J
9,lr,german,Alg1,0,0.1,0.01,11.535425,0.992060,0.971308,0.029111,0.144466
18,lr,german,Alg1,0,0.1,0.10,4.044556,0.813284,0.713148,0.338066,0.742522
32,lr,german,Alg1,1,0.1,0.01,15.956258,0.989983,0.954210,0.046871,0.206434
41,lr,german,Alg1,1,0.1,0.10,3.564100,0.677389,0.580620,0.546476,0.902886
55,lr,german,Alg1,2,0.1,0.01,11.986345,0.992976,0.971989,0.028411,0.148274
...,...,...,...,...,...,...,...,...,...,...,...
1381,nn,sba,ROARL1,2,0.1,0.10,3.917083,0.907788,0.891276,0.115186,0.506894
1392,nn,sba,ROARL1,3,0.1,0.01,12.869033,0.953011,0.941231,0.060591,0.189281
1393,nn,sba,ROARL1,3,0.1,0.10,5.465867,0.917390,0.899980,0.105452,0.652039
1404,nn,sba,ROARL1,4,0.1,0.01,6.427334,0.794834,0.787485,2.831217,2.895491
1405,nn,sba,ROARL1,4,0.1,0.10,3.103700,0.754834,0.740534,2.882453,3.192823

In [16]:
df_results_sampled['lambda'] = df_results_sampled['lambda'].astype(str)
df_results_sampled['model'] = df_results_sampled['model'].replace(['lr', 'nn'], ['LR', 'NN'])
df_results_sampled['dataset'] = df_results_sampled['dataset'].replace(['german', 'sba'], ['German', 'SBA'])

pvt = df_results_sampled.pivot_table(values='J', index=['model', 'algorithm'], columns=['dataset', 'lambda'], aggfunc=["mean", "std"])
# pvt = df_results_sampled.pivot_table(values=['Current Validity', 'Worst Case Validity','Cost','J'], index=['model', 'algorithm'], columns=['dataset', 'lambda'], aggfunc=["mean", "std"])

lambda_order = ["0.1", "0.01", "0.001"]
algorithm_order = ['Alg1', 'ROARLInf', 'L1PSD', 'ROARL1']
pvt = pvt.reindex(columns=lambda_order, level="lambda").reindex(index=algorithm_order, level="algorithm")
pvt = pvt.rename(index={'Alg1': 'LInf'}, level='algorithm')
pvt.index.set_names(["Model", "Algorithm"], inplace=True)
pvt.columns.set_names([None ,"Dataset", "Lambda"], inplace=True)
pvt.style

In [17]:
lr_linf_pct = ((pvt.loc['LR', 'ROARLInf'] - pvt.loc['LR', 'LInf']) * 100 / pvt.loc['LR', 'LInf']).round(0).astype(int)
lr_linf_pct = lr_linf_pct.loc['mean'].astype(str)
lr_l1_pct = ((pvt.loc['LR', 'ROARL1'] - pvt.loc['LR', 'L1PSD']) * 100 / pvt.loc['LR', 'L1PSD']).round(0).astype(int)
lr_l1_pct = lr_l1_pct.loc['mean'].astype(str)
nn_linf_pct = ((pvt.loc['NN', 'ROARLInf'] - pvt.loc['NN', 'LInf']) * 100 / pvt.loc['NN', 'LInf']).round(0).astype(int)
nn_linf_pct = nn_linf_pct.loc['mean'].astype(str)
nn_l1_pct = ((pvt.loc['NN', 'ROARL1'] - pvt.loc['NN', 'L1PSD']) * 100 / pvt.loc['NN', 'L1PSD']).round(0).astype(int)
nn_l1_pct = nn_l1_pct.loc['mean'].astype(str)

In [18]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

new_pvt.loc['LR', 'ROARLInf'] += " (" + lr_linf_pct + "%)"
new_pvt.loc['LR', 'ROARL1'] += " (" + lr_l1_pct + "%)"
new_pvt.loc['NN', 'ROARLInf'] += " (" + nn_linf_pct + "%)"
new_pvt.loc['NN', 'ROARL1'] += " (" + nn_l1_pct + "%)"

new_pvt.style

In [14]:
means.index.get_level_values('Model').unique()

NameError: name 'means' is not defined

In [ ]:
means = pvt['mean']                       # numeric
formatted = new_pvt.copy()                # your "mean ± std" strings

# 2) build a mask: True where the cell should be bold
mask = pd.DataFrame(False, index=formatted.index, columns=formatted.columns)
pairs = [('LInf', 'ROARLInf'), ('L1PSD', 'ROARL1')]

for model in means.index.get_level_values('Model').unique():
    for a1, a2 in pairs:
        s1 = means.loc[(model, a1)]
        s2 = means.loc[(model, a2)]
        mask.loc[(model, a1)] = True if s1 <= s2 else False
        mask.loc[(model, a2)] = False if 

# for model in means.index.get_level_values('Model').unique():
#     for a1, a2 in pairs:
#         if (model, a1) in means.index and (model, a2) in means.index:
#             s1 = means.loc[(model, a1)]   # row (Series over columns)
#             s2 = means.loc[(model, a2)]
#             # bold the lower value; bold both on ties
#             mask.loc[(model, a1)] = (s1 <= s2).reindex(mask.columns, fill_value=False)
#             mask.loc[(model, a2)] = (s2 <  s1).reindex(mask.columns, fill_value=False)

# # 3) apply style to the string table
# def bold_where(df):
#     return pd.DataFrame(
#         np.where(mask, 'font-weight:700', ''),
#         index=df.index, columns=df.columns
#     )

# styled = (
#     formatted.style
#     .apply(bold_where, axis=None)
#     .set_table_styles([
#         {"selector": "th", "props": [("text-align", "left")]},   # headers + index
#         {"selector": "td", "props": [("text-align", "left")]}    # data cells
#     ])
# )

# styled
means.loc[(model, a1)]

Dataset  Lambda
German   0.1       0.313893
         0.01      0.055770
         0.001     0.008283
SBA      0.1       0.793413
         0.01      0.523810
         0.001     0.488111
Name: (NN, L1PSD), dtype: float64

# Two Lambda - All Metric

In [80]:
df_results_sampled = df_results[df_results['lambda'].isin([0.001])]
df_results_sampled

,model,dataset,algorithm,seed,alpha,lambda,Cost,Current Validity,Worst Case Validity,BCE Loss,J
0,lr,german,Alg1,0,0.1,0.001,18.215356,0.999600,0.997130,0.002874,0.021089
23,lr,german,Alg1,1,0.1,0.001,26.691817,0.999668,0.995420,0.004590,0.031282
46,lr,german,Alg1,2,0.1,0.001,18.510436,0.999641,0.997200,0.002804,0.021315
69,lr,german,Alg1,3,0.1,0.001,17.216407,0.999597,0.997252,0.002752,0.019968
92,lr,german,Alg1,4,0.1,0.001,20.724150,0.999643,0.996782,0.003224,0.023948
...,...,...,...,...,...,...,...,...,...,...,...
1355,nn,sba,ROARL1,0,0.1,0.001,9.084767,0.961250,0.953268,0.047872,0.056957
1367,nn,sba,ROARL1,1,0.1,0.001,9.748867,0.959120,0.950992,0.050257,0.060006
1379,nn,sba,ROARL1,2,0.1,0.001,10.135900,0.959910,0.951821,0.049388,0.059524
1391,nn,sba,ROARL1,3,0.1,0.001,14.345850,0.959031,0.948643,0.052740,0.067085
1403,nn,sba,ROARL1,4,0.1,0.001,7.714700,0.800109,0.793729,2.824634,2.832348

In [81]:
df_results_sampled['lambda'] = df_results_sampled['lambda'].astype(str)
df_results_sampled['model'] = df_results_sampled['model'].replace(['lr', 'nn'], ['LR', 'NN'])
df_results_sampled['dataset'] = df_results_sampled['dataset'].replace(['german', 'sba'], ['German', 'SBA'])

pvt = df_results_sampled.pivot_table(values=['Current Validity', 'Worst Case Validity','Cost','J'], index=['model', 'algorithm'], columns=['dataset', 'lambda'], aggfunc=["mean", "std"])

pvt = pvt.rename(index={'Alg1': 'LInf'}, level='algorithm')
pvt.index.set_names(["Model", "Algorithm"], inplace=True)
pvt.columns.set_names(['AggFunc', 'Metric', 'Dataset', 'Lambda'], inplace=True)
pvt.columns = pvt.columns.reorder_levels(['AggFunc', 'Dataset', 'Lambda', 'Metric'])
pvt = pvt.sort_index(axis=1)

lambda_order = ["0.1", "0.01", "0.001"]
metric_order = ["Current Validity", "Worst Case Validity", "Cost", "J"]
algorithm_order = ['LInf', 'ROARLInf', 'L1PSD', 'ROARL1']
pvt = pvt.reindex(columns=lambda_order, level="Lambda").reindex(columns=metric_order, level= "Metric").reindex(index=algorithm_order, level="Algorithm")

pvt.style

In [82]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

In [83]:
new_pvt.style

In [84]:
lr_linf_pct = ((pvt.loc['LR', 'ROARLInf'] - pvt.loc['LR', 'LInf']) * 100 / pvt.loc['LR', 'LInf']).round(0).astype(int)
lr_linf_pct = lr_linf_pct.loc['mean'].astype(str)
lr_l1_pct = ((pvt.loc['LR', 'ROARL1'] - pvt.loc['LR', 'L1PSD']) * 100 / pvt.loc['LR', 'L1PSD']).round(0).astype(int)
lr_l1_pct = lr_l1_pct.loc['mean'].astype(str)
nn_linf_pct = ((pvt.loc['NN', 'ROARLInf'] - pvt.loc['NN', 'LInf']) * 100 / pvt.loc['NN', 'LInf']).round(0).astype(int)
nn_linf_pct = nn_linf_pct.loc['mean'].astype(str)
nn_l1_pct = ((pvt.loc['NN', 'ROARL1'] - pvt.loc['NN', 'L1PSD']) * 100 / pvt.loc['NN', 'L1PSD']).round(0).astype(int)
nn_l1_pct = nn_l1_pct.loc['mean'].astype(str)

In [85]:
# new_pvt.loc['LR', 'ROARLInf'] += " (" + lr_linf_pct + "%)"
# new_pvt.loc['LR', 'ROARL1'] += " (" + lr_l1_pct + "%)"
# new_pvt.loc['NN', 'ROARLInf'] += " (" + nn_linf_pct + "%)"
# new_pvt.loc['NN', 'ROARL1'] += " (" + nn_l1_pct + "%)"

new_pvt.loc['LR', 'ROARLInf'] = "(" + lr_linf_pct + "%) " + new_pvt.loc['LR', 'ROARLInf']
new_pvt.loc['LR', 'ROARL1'] = "(" + lr_l1_pct + "%) " + new_pvt.loc['LR', 'ROARL1']
new_pvt.loc['NN', 'ROARLInf'] = "(" + nn_linf_pct + "%) " + new_pvt.loc['NN', 'ROARLInf']
new_pvt.loc['NN', 'ROARL1'] = "(" + nn_l1_pct + "%) " + new_pvt.loc['NN', 'ROARL1']

In [86]:
new_pvt.style

In [87]:
means = pvt['mean']

mask = pd.DataFrame(False, index=new_pvt.index, columns=new_pvt.columns)
pairs = [('LInf', 'ROARLInf'), ('L1PSD', 'ROARL1')]

for model in means.index.get_level_values('Model').unique():
    for alg1, alg2 in pairs:
        s1 = means.loc[(model, alg1)]
        s2 = means.loc[(model, alg2)]

        metrics = s1.index.get_level_values('Metric').unique()

        for metric in metrics:
            match metric:
                case "J" | "Cost":
                    mask.loc[(model, alg1),(slice(None), slice(None), metric)] = s1.loc[:,:, metric] <= s2.loc[:,:, metric]
                    mask.loc[(model, alg2),(slice(None), slice(None), metric)] = s2.loc[:,:, metric] < s1.loc[:,:, metric]
                case "Current Validity" | "Worst Case Validity":
                    mask.loc[(model, alg1),(slice(None), slice(None), metric)] = s1.loc[:,:, metric] >= s2.loc[:,:, metric]
                    mask.loc[(model, alg2),(slice(None), slice(None), metric)] = s2.loc[:,:, metric] > s1.loc[:,:, metric]

                case _:
                    print(f"{metric} is not implemented")


# for model in means.index.get_level_values('Model').unique():
#     for a1, a2 in pairs:
#         if (model, a1) in means.index and (model, a2) in means.index:
#             s1 = means.loc[(model, a1)]   # row (Series over columns)
#             s2 = means.loc[(model, a2)]
#             # bold the lower value; bold both on ties
#             mask.loc[(model, a1)] = (s1 <= s2).reindex(mask.columns, fill_value=False)
#             mask.loc[(model, a2)] = (s2 <  s1).reindex(mask.columns, fill_value=False)

def bold_where(df):
    return pd.DataFrame(np.where(mask, 'font-weight:bold', ''), index=df.index, columns=df.columns)

# new_pvt_styled = new_pvt.copy(deep=True)
new_pvt_styled = (new_pvt.style.apply(bold_where, axis=None))
new_pvt_styled

# One Lambda All Metric

In [352]:
df_results_sampled = df_results[df_results['lambda'].isin([0.1])]
df_results_sampled

,model,dataset,algorithm,seed,alpha,lambda,Cost,Current Validity,Worst Case Validity,BCE Loss,J
18,lr,german,Alg1,0,0.1,0.1,4.044556,0.813284,0.713148,0.338066,0.742522
41,lr,german,Alg1,1,0.1,0.1,3.564100,0.677389,0.580620,0.546476,0.902886
64,lr,german,Alg1,2,0.1,0.1,4.692264,0.836227,0.719806,0.328774,0.798000
87,lr,german,Alg1,3,0.1,0.1,3.695547,0.824048,0.725373,0.321069,0.690624
110,lr,german,Alg1,4,0.1,0.1,4.649043,0.794955,0.677940,0.388697,0.853601
...,...,...,...,...,...,...,...,...,...,...,...
1352,nn,sba,ROARL1,0,0.1,0.1,3.310300,0.917970,0.902227,0.102929,0.433959
1364,nn,sba,ROARL1,1,0.1,0.1,3.630617,0.907155,0.889711,0.117017,0.480078
1376,nn,sba,ROARL1,2,0.1,0.1,3.917083,0.907788,0.891276,0.115186,0.506894
1388,nn,sba,ROARL1,3,0.1,0.1,5.465867,0.917390,0.899980,0.105452,0.652039
1400,nn,sba,ROARL1,4,0.1,0.1,3.103700,0.754834,0.740534,2.882453,3.192823

In [356]:
df_results_sampled['lambda'] = df_results_sampled['lambda'].astype(str)
df_results_sampled['model'] = df_results_sampled['model'].replace(['lr', 'nn'], ['LR', 'NN'])
df_results_sampled['dataset'] = df_results_sampled['dataset'].replace(['german', 'sba'], ['German', 'SBA'])

pvt = df_results_sampled.pivot_table(values=['Current Validity', 'Worst Case Validity','Cost','J'], index=['model', 'algorithm'], columns=['dataset'], aggfunc=["mean", "std"])

pvt = pvt.rename(index={'Alg1': 'LInf'}, level='algorithm')
pvt.index.set_names(["Model", "Algorithm"], inplace=True)
pvt.columns.set_names(['AggFunc', 'Metric', 'Dataset'], inplace=True)
pvt.columns = pvt.columns.reorder_levels(['AggFunc', 'Dataset', 'Metric'])
pvt = pvt.sort_index(axis=1)

lambda_order = ["0.1", "0.01"]
metric_order = ["Current Validity", "Worst Case Validity", "Cost", "J"]
algorithm_order = ['LInf', 'ROARLInf', 'L1PSD', 'ROARL1']
pvt = pvt.reindex(columns=metric_order, level= "Metric").reindex(index=algorithm_order, level="Algorithm")

pvt.style

In [359]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

new_pvt.style

In [360]:
lr_linf_pct = ((pvt.loc['LR', 'ROARLInf'] - pvt.loc['LR', 'LInf']) * 100 / pvt.loc['LR', 'LInf']).round(0).astype(int)
lr_linf_pct = lr_linf_pct.loc['mean'].astype(str)
lr_l1_pct = ((pvt.loc['LR', 'ROARL1'] - pvt.loc['LR', 'L1PSD']) * 100 / pvt.loc['LR', 'L1PSD']).round(0).astype(int)
lr_l1_pct = lr_l1_pct.loc['mean'].astype(str)
nn_linf_pct = ((pvt.loc['NN', 'ROARLInf'] - pvt.loc['NN', 'LInf']) * 100 / pvt.loc['NN', 'LInf']).round(0).astype(int)
nn_linf_pct = nn_linf_pct.loc['mean'].astype(str)
nn_l1_pct = ((pvt.loc['NN', 'ROARL1'] - pvt.loc['NN', 'L1PSD']) * 100 / pvt.loc['NN', 'L1PSD']).round(0).astype(int)
nn_l1_pct = nn_l1_pct.loc['mean'].astype(str)

new_pvt.loc['LR', 'ROARLInf'] += " (" + lr_linf_pct + "%)"
new_pvt.loc['LR', 'ROARL1'] += " (" + lr_l1_pct + "%)"
new_pvt.loc['NN', 'ROARLInf'] += " (" + nn_linf_pct + "%)"
new_pvt.loc['NN', 'ROARL1'] += " (" + nn_l1_pct + "%)"

new_pvt.style

# One Lambda - LInf vs L1

In [372]:
df_results_sampled = df_results[df_results['lambda'].isin([0.01]) & df_results['algorithm'].isin(['Alg1', 'L1PSD'])]
df_results_sampled

,model,dataset,algorithm,seed,alpha,lambda,Cost,Current Validity,Worst Case Validity,BCE Loss,J
9,lr,german,Alg1,0,0.1,0.01,11.535425,0.992060,0.971308,0.029111,0.144466
32,lr,german,Alg1,1,0.1,0.01,15.956258,0.989983,0.954210,0.046871,0.206434
55,lr,german,Alg1,2,0.1,0.01,11.986345,0.992976,0.971989,0.028411,0.148274
78,lr,german,Alg1,3,0.1,0.01,10.824120,0.992229,0.972529,0.027855,0.136096
101,lr,german,Alg1,4,0.1,0.01,13.212443,0.992274,0.967806,0.032723,0.164848
119,lr,german,L1PSD,0,0.1,0.01,9.887512,0.982088,0.974062,0.026280,0.125155
126,lr,german,L1PSD,1,0.1,0.01,13.736950,0.974823,0.955818,0.045188,0.182558
133,lr,german,L1PSD,2,0.1,0.01,10.075509,0.983539,0.975253,0.025058,0.125814
140,lr,german,L1PSD,3,0.1,0.01,9.124467,0.982960,0.975716,0.024584,0.115829
147,lr,german,L1PSD,4,0.1,0.01,11.479343,0.980024,0.969386,0.031093,0.145886
401,lr,sba,Alg1,0,0.1,0.01,3.320900,0.999321,0.996862,0.003143,0.036352
414,lr,sba,Alg1,1,0.1,0.01,3.167767,0.999296,0.996821,0.003184,0.034862
427,lr,sba,Alg1,2,0.1,0.01,3.345083,0.999295,0.996775,0.003231,0.036681
440,lr,sba,Alg1,3,0.1,0.01,3.714250,0.999348,0.996915,0.003090,0.040232
453,lr,sba,Alg1,4,0.1,0.01,4.349733,0.999438,0.997015,0.002989,0.046486
466,lr,sba,L1PSD,0,0.1,0.01,2.918433,0.997447,0.996957,0.003048,0.032232
474,lr,sba,L1PSD,1,0.1,0.01,2.762883,0.997399,0.996918,0.003087,0.030716
482,lr,sba,L1PSD,2,0.1,0.01,2.928133,0.997330,0.996874,0.003131,0.032413
490,lr,sba,L1PSD,3,0.1,0.01,3.318083,0.997561,0.997006,0.002998,0.036179
498,lr,sba,L1PSD,4,0.1,0.01,3.905883,0.997882,0.997101,0.002903,0.041962
694,nn,german,Alg1,0,0.1,0.01,4.112633,0.995584,0.990489,0.009567,0.050693
726,nn,german,Alg1,1,0.1,0.01,5.389020,0.994802,0.990384,0.009665,0.063556
758,nn,german,Alg1,2,0.1,0.01,4.763787,0.996337,0.991382,0.008661,0.056299
790,nn,german,Alg1,3,0.1,0.01,4.945583,0.995373,0.987824,0.012272,0.061728
822,nn,german,Alg1,4,0.1,0.01,5.543471,0.992965,0.984853,0.015332,0.070767
850,nn,german,L1PSD,0,0.1,0.01,3.707278,0.993126,0.990658,0.009394,0.046467
857,nn,german,L1PSD,1,0.1,0.01,5.029840,0.992175,0.990436,0.009611,0.059910
864,nn,german,L1PSD,2,0.1,0.01,4.600350,0.993155,0.990803,0.009248,0.055251
871,nn,german,L1PSD,3,0.1,0.01,4.048767,0.991354,0.987823,0.012274,0.052762
878,nn,german,L1PSD,4,0.1,0.01,4.894914,0.987807,0.984692,0.015509,0.064459
1203,nn,sba,Alg1,0,0.1,0.01,2.891567,0.999354,0.997138,0.002866,0.031782
1213,nn,sba,Alg1,1,0.1,0.01,3.212033,0.999275,0.996717,0.003289,0.035409
1223,nn,sba,Alg1,2,0.1,0.01,3.308867,0.999297,0.996789,0.003217,0.036305
1233,nn,sba,Alg1,3,0.1,0.01,3.857333,0.999397,0.997144,0.002860,0.041433
1243,nn,sba,Alg1,4,0.1,0.01,9.520300,0.832809,0.831098,2.418721,2.513924
1251,nn,sba,L1PSD,0,0.1,0.01,2.561333,0.997677,0.997233,0.002771,0.028385
1259,nn,sba,L1PSD,1,0.1,0.01,2.781583,0.997249,0.996754,0.003252,0.031067
1267,nn,sba,L1PSD,2,0.1,0.01,2.888900,0.997305,0.996891,0.003114,0.032003
1275,nn,sba,L1PSD,3,0.1,0.01,3.435550,0.997792,0.997282,0.002722,0.037077
1283,nn,sba,L1PSD,4,0.1,0.01,7.189533,0.831504,0.831195,2.418624,2.490520

In [373]:
df_results_sampled['lambda'] = df_results_sampled['lambda'].astype(str)
df_results_sampled['model'] = df_results_sampled['model'].replace(['lr', 'nn'], ['LR', 'NN'])
df_results_sampled['dataset'] = df_results_sampled['dataset'].replace(['german', 'sba'], ['German', 'SBA'])

pvt = df_results_sampled.pivot_table(values=['Current Validity', 'Worst Case Validity','Cost','J'], index=['model', 'algorithm'], columns=['dataset'], aggfunc=["mean", "std"])

pvt = pvt.rename(index={'Alg1': 'LInf'}, level='algorithm')
pvt.index.set_names(["Model", "Algorithm"], inplace=True)
pvt.columns.set_names(['AggFunc', 'Metric', 'Dataset'], inplace=True)
pvt.columns = pvt.columns.reorder_levels(['AggFunc', 'Dataset', 'Metric'])
pvt = pvt.sort_index(axis=1)

metric_order = ["Current Validity", "Worst Case Validity", "Cost", "J"]
algorithm_order = ['L1PSD', 'LInf']
pvt = pvt.reindex(columns=metric_order, level= "Metric").reindex(index=algorithm_order, level="Algorithm")

pvt.style

In [374]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

new_pvt.style

In [375]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

lr_linf_pct = ((pvt.loc['LR', 'LInf'] - pvt.loc['LR', 'L1PSD']) * 100 / pvt.loc['LR', 'L1PSD']).round(0).astype(int)
lr_linf_pct = lr_linf_pct.loc['mean'].astype(str)
nn_linf_pct = ((pvt.loc['NN', 'LInf'] - pvt.loc['NN', 'L1PSD']) * 100 / pvt.loc['NN', 'L1PSD']).round(0).astype(int)
nn_linf_pct = nn_linf_pct.loc['mean'].astype(str)

new_pvt.loc['LR', 'LInf'] = "(" + lr_linf_pct + "%) " + new_pvt.loc['LR', 'LInf']
new_pvt.loc['NN', 'LInf'] = "(" + nn_linf_pct + "%) " + new_pvt.loc['NN', 'LInf']

new_pvt.style

# One Lambda - LInf vs L1 (Different Lambd by Dataset)

In [377]:
df_results_sampled = df_results[df_results['algorithm'].isin(['Alg1', 'L1PSD'])]
df_results_sampled

,model,dataset,algorithm,seed,alpha,lambda,Cost,Current Validity,Worst Case Validity,BCE Loss,J
0,lr,german,Alg1,0,0.1,0.1,4.044556,0.813284,0.713148,0.338066,0.742522
1,lr,german,Alg1,1,0.1,0.1,3.564100,0.677389,0.580620,0.546476,0.902886
2,lr,german,Alg1,2,0.1,0.1,4.692264,0.836227,0.719806,0.328774,0.798000
3,lr,german,Alg1,3,0.1,0.1,3.695547,0.824048,0.725373,0.321069,0.690624
4,lr,german,Alg1,4,0.1,0.1,4.649043,0.794955,0.677940,0.388697,0.853601
5,lr,german,L1PSD,0,0.1,0.1,3.834094,0.798330,0.770316,0.260986,0.644396
6,lr,german,L1PSD,1,0.1,0.1,3.866700,0.727446,0.682209,0.382457,0.769127
7,lr,german,L1PSD,2,0.1,0.1,4.277773,0.813215,0.775984,0.253682,0.681459
8,lr,german,L1PSD,3,0.1,0.1,3.464153,0.808592,0.782608,0.245123,0.591539
9,lr,german,L1PSD,4,0.1,0.1,4.172600,0.769223,0.727249,0.319043,0.736303
20,lr,sba,Alg1,0,0.1,0.7,1.951150,0.942295,0.793318,0.231531,1.597336
21,lr,sba,Alg1,1,0.1,0.7,1.790100,0.941874,0.790756,0.234766,1.487836
22,lr,sba,Alg1,2,0.1,0.7,1.942650,0.940836,0.785626,0.241295,1.601150
23,lr,sba,Alg1,3,0.1,0.7,2.357833,0.943261,0.792449,0.232655,1.883138
24,lr,sba,Alg1,4,0.1,0.7,3.038833,0.952076,0.800874,0.222066,2.349250
25,lr,sba,L1PSD,0,0.1,0.7,1.557250,0.815131,0.787012,0.239511,1.329586
26,lr,sba,L1PSD,1,0.1,0.7,1.384550,0.811870,0.784319,0.242940,1.212125
27,lr,sba,L1PSD,2,0.1,0.7,1.527317,0.807178,0.781264,0.246843,1.315964
28,lr,sba,L1PSD,3,0.1,0.7,1.981717,0.822963,0.790480,0.235114,1.622316
29,lr,sba,L1PSD,4,0.1,0.7,2.613383,0.846755,0.797074,0.226808,2.056176
40,nn,german,Alg1,0,0.1,0.3,1.019511,0.851043,0.792302,0.236145,0.541998
41,nn,german,Alg1,1,0.1,0.3,1.486633,0.815956,0.735513,0.312028,0.758018
42,nn,german,Alg1,2,0.1,0.3,1.417117,0.851556,0.784390,0.251188,0.676323
43,nn,german,Alg1,3,0.1,0.3,1.295878,0.854692,0.785293,0.253865,0.642628
44,nn,german,Alg1,4,0.1,0.3,1.423876,0.779963,0.695626,0.371407,0.798570
45,nn,german,L1PSD,0,0.1,0.3,0.828600,0.821913,0.801353,0.225078,0.473658
46,nn,german,L1PSD,1,0.1,0.3,1.211607,0.764252,0.730542,0.320042,0.683524
47,nn,german,L1PSD,2,0.1,0.3,1.254017,0.812537,0.788093,0.244850,0.621055
48,nn,german,L1PSD,3,0.1,0.3,1.095022,0.837599,0.808476,0.219723,0.548229
49,nn,german,L1PSD,4,0.1,0.3,1.030762,0.724471,0.692171,0.384976,0.694205
60,nn,sba,Alg1,0,0.1,0.7,1.661333,0.948945,0.808854,0.212375,1.375309
61,nn,sba,Alg1,1,0.1,0.7,1.785617,0.939168,0.783044,0.245372,1.495304
62,nn,sba,Alg1,2,0.1,0.7,1.922183,0.942980,0.787281,0.239672,1.585201
63,nn,sba,Alg1,3,0.1,0.7,2.615783,0.950540,0.807478,0.214226,2.045275
64,nn,sba,Alg1,4,0.1,0.7,1.317483,0.792517,0.684884,3.304371,4.226609
65,nn,sba,L1PSD,0,0.1,0.7,1.328950,0.832284,0.806263,0.215504,1.145769
66,nn,sba,L1PSD,1,0.1,0.7,1.337217,0.803586,0.775895,0.254541,1.190593
67,nn,sba,L1PSD,2,0.1,0.7,1.505017,0.807393,0.784909,0.242696,1.296208
68,nn,sba,L1PSD,3,0.1,0.7,2.226050,0.840113,0.809727,0.211353,1.769588
69,nn,sba,L1PSD,4,0.1,0.7,1.039000,0.702591,0.684398,2.948196,3.675496

In [378]:
df_results_sampled['lambda'] = df_results_sampled['lambda'].astype(str)
df_results_sampled['model'] = df_results_sampled['model'].replace(['lr', 'nn'], ['LR', 'NN'])
df_results_sampled['dataset'] = df_results_sampled['dataset'].replace(['german', 'sba'], ['German', 'SBA'])

pvt = df_results_sampled.pivot_table(values=['Current Validity', 'Worst Case Validity','Cost','J'], index=['model', 'algorithm'], columns=['dataset'], aggfunc=["mean", "std"])

pvt = pvt.rename(index={'Alg1': 'LInf'}, level='algorithm')
pvt.index.set_names(["Model", "Algorithm"], inplace=True)
pvt.columns.set_names(['AggFunc', 'Metric', 'Dataset'], inplace=True)
pvt.columns = pvt.columns.reorder_levels(['AggFunc', 'Dataset', 'Metric'])
pvt = pvt.sort_index(axis=1)

metric_order = ["Current Validity", "Worst Case Validity", "Cost", "J"]
algorithm_order = ['L1PSD', 'LInf']
pvt = pvt.reindex(columns=metric_order, level= "Metric").reindex(index=algorithm_order, level="Algorithm")

pvt.style

In [379]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

new_pvt.style

In [380]:
new_pvt = pvt['mean'].round(4).applymap(lambda x: f"{x:.4f}").astype(str) + ' \u00B1 ' + \
    pvt['std'].round(2).applymap(lambda x: f"{x:.2f}").astype(str)

lr_linf_pct = ((pvt.loc['LR', 'LInf'] - pvt.loc['LR', 'L1PSD']) * 100 / pvt.loc['LR', 'L1PSD']).round(0).astype(int)
lr_linf_pct = lr_linf_pct.loc['mean'].astype(str)
nn_linf_pct = ((pvt.loc['NN', 'LInf'] - pvt.loc['NN', 'L1PSD']) * 100 / pvt.loc['NN', 'L1PSD']).round(0).astype(int)
nn_linf_pct = nn_linf_pct.loc['mean'].astype(str)

new_pvt.loc['LR', 'LInf'] = "(" + lr_linf_pct + "%) " + new_pvt.loc['LR', 'LInf']
new_pvt.loc['NN', 'LInf'] = "(" + nn_linf_pct + "%) " + new_pvt.loc['NN', 'LInf']

new_pvt.style