In [3]:
import numpy as np
import pandas as pd
import os

In [33]:
def calThetaAdv_l1(xP: np.ndarray, theta0: np.ndarray, alpha):
    thetaP = theta0.copy()
    i = np.argmax(np.abs(xP))
    thetaP[i] -= (alpha * np.sign(xP[i]))

    return thetaP

def calThetaAdv_linf(xP: np.ndarray, weights: np.ndarray, bias, alpha):
    # xP does not have bias
    weights_adv = weights - (alpha * np.sign(xP))

    for i in range(len(xP)):
        if np.sign(xP[i]) == 0:
            weights_adv[i] = weights_adv[i] - (alpha * np.sign(weights_adv[i]))
    bias_adv = bias - alpha

    return np.concat((weights_adv, [bias_adv]))

def getStats(self, xP: np.ndarray, x0: np.ndarray, theta: np.ndarray, lamb):
    if xP.size != theta.size:
        x0 = np.hstack((x0, 1))
        xP = np.hstack((xP, 1))

    return np.log(1 + np.exp(-(x @ theta))) + \
        (lamb * (np.linalg.norm(x0 - x, ord=1)))

In [ ]:
dir_path = "../results/recourse"
file_name = "lr_synthetic_Alg1_0.pkl"
final_path = os.path.join(dir_path, file_name)

df1 = pd.read_pickle(final_path)

# Analysis
df1["theta_r"] = df1.apply(lambda row : calThetaAdv_linf(row['x_r'], row['theta_0'][:-1], row['theta_0'][-1], row['alpha']), axis=1)
df1['J'] =

,algorithm,seed,alpha,lambda,i,x_0,x_r,theta_0,theta_r
0,Alg1,0,0.5,0.1,0,"[-2.3862, -1.7774]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
1,Alg1,0,0.5,0.1,1,"[-2.7105, -1.7402]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
2,Alg1,0,0.5,0.1,2,"[-2.3817, -1.9247]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
3,Alg1,0,0.5,0.1,3,"[-2.337, -1.0178]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
4,Alg1,0,0.5,0.1,4,"[-2.402, -2.7282]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
...,...,...,...,...,...,...,...,...,...
91,Alg1,0,0.5,0.1,91,"[-1.7741, -2.2538]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
92,Alg1,0,0.5,0.1,92,"[-2.2471, -3.4363]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
93,Alg1,0,0.5,0.1,93,"[-1.2901, -2.4369]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
94,Alg1,0,0.5,0.1,94,"[-2.911, -1.7206]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"
95,Alg1,0,0.5,0.1,95,"[-1.0356, -1.6137]","[0.0, 2.085]","[1.9661, 1.9713, 0.0506]","[1.4661, 1.4713, -0.4494]"

In [31]:
dir_path = "../results/recourse"
file_name = "lr_synthetic_L1PSD_0.pkl"
final_path = os.path.join(dir_path, file_name)

df2 = pd.read_pickle(final_path)
df2['theta_r'] = df2.apply(lambda row : calThetaAdv_l1(np.hstack((row['x_r'], 1)), row['theta_0'], row['alpha']), axis=1)
df2

,algorithm,seed,alpha,lambda,i,x_0,x_r,theta_0,theta_r
0,L1PSD,0,0.5,0.1,0,"[-2.3862, -1.7774]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
1,L1PSD,0,0.5,0.1,1,"[-2.7105, -1.7402]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
2,L1PSD,0,0.5,0.1,2,"[-2.3817, -1.9247]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
3,L1PSD,0,0.5,0.1,3,"[-2.337, -1.0178]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
4,L1PSD,0,0.5,0.1,4,"[-2.402, -2.7282]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
...,...,...,...,...,...,...,...,...,...
91,L1PSD,0,0.5,0.1,91,"[-1.7741, -2.2538]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
92,L1PSD,0,0.5,0.1,92,"[-2.2471, -3.4363]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
93,L1PSD,0,0.5,0.1,93,"[-1.2901, -2.4369]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
94,L1PSD,0,0.5,0.1,94,"[-2.911, -1.7206]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"
95,L1PSD,0,0.5,0.1,95,"[-1.0356, -1.6137]","[0.7171, 1.0]","[1.9661, 1.9713, 0.0506]","[1.9661, 1.4713, 0.0506]"

In [ ]:
dir_path = "../results/recourse"
file_name = "lr_synthetic_ROAR_0.pkl"
final_path = os.path.join(dir_path, file_name)

df3 = pd.read_pickle(final_path)

,algorithm,seed,alpha,lambda,i,x_0,x_r,theta_0
0,ROAR,0,0.5,0.1,0,"[-2.3862, -1.7774]","[0.3794, 0.8222]","[1.9661, 1.9713, 0.0506]"
1,ROAR,0,0.5,0.1,1,"[-2.7105, -1.7402]","[0.2405, 0.9448]","[1.9661, 1.9713, 0.0506]"
2,ROAR,0,0.5,0.1,2,"[-2.3817, -1.9247]","[0.4369, 0.7677]","[1.9661, 1.9713, 0.0506]"
3,ROAR,0,0.5,0.1,3,"[-2.337, -1.0178]","[0.0955, 1.0694]","[1.9661, 1.9713, 0.0506]"
4,ROAR,0,0.5,0.1,4,"[-2.402, -2.7282]","[0.7175, 0.4867]","[1.9661, 1.9713, 0.0506]"
...,...,...,...,...,...,...,...,...
91,ROAR,0,0.5,0.1,91,"[-1.7741, -2.2538]","[0.7767, 0.4302]","[1.9661, 1.9713, 0.0506]"
92,ROAR,0,0.5,0.1,92,"[-2.2471, -3.4363]","[1.0089, 0.1598]","[1.9661, 1.9713, 0.0506]"
93,ROAR,0,0.5,0.1,93,"[-1.2901, -2.4369]","[1.0113, 0.1709]","[1.9661, 1.9713, 0.0506]"
94,ROAR,0,0.5,0.1,94,"[-2.911, -1.7206]","[0.1547, 1.0144]","[1.9661, 1.9713, 0.0506]"
95,ROAR,0,0.5,0.1,95,"[-1.0356, -1.6137]","[0.8281, 0.3923]","[1.9661, 1.9713, 0.0506]"